stages:
  - build-backend-docker
  - run-backend-docker
  # - docker-down

build-backend-docker:
  stage: build-backend-docker
  tags:
    - docker
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_REF_NAME =~ "main"
  script:
    - docker build -t myorg/myapp .

run-backend-docker:
  stage: run-backend-docker
  tags:
    - docker
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_REF_NAME =~ "main"
  script:
    - docker run -p 8080:8080 myorg/myapp

docker-down:
  stage: docker-down
  tags:
    - docker
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_REF_NAME =~ "main"
  script:
    - docker-compose -f docker-compose.yaml down
